version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    volumes:
        - esdata1:/usr/share/elasticsearch/data
    ports:
        - 9200:9200
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
          - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    links:
        - elasticsearch:elasticsearch
    ports:
        - 5601:5601

volumes:
  esdata1:
    driver: local